<?php
/*
 * Copyright Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Mollie\HyvaCheckout\Magewire\Checkout\Payment\Method\WithIssuer $block */
$magewire = $block->getMagewire();
?>
<div>
    <select wire:model="selectedIssuer">
        <option value=""><?= $escaper->escapeHtml(__('Please select')->render()); ?></option>
        <?php foreach ($magewire->issuers as $issuer): ?>
            <option value="<?= $escaper->escapeHtmlAttr($issuer['id']); ?>"><?= $escaper->escapeHtml($issuer['name']); ?></option>
        <?php endforeach; ?>
    </select>
</div>
